"""Minimal V4 execution boundary for replaceable external providers."""

from .text_generation import (
    DeepSeekTextProvider,
    FakeTextProvider,
    ProviderConfigurationError,
    ProviderMalformedResponseError,
    ProviderTimeoutError,
    ProviderUnavailableError,
    TextGenerationRequest,
    TextMessage,
    TextProvider,
    TextProviderError,
    create_text_provider_from_environment,
)
from .media_jobs import (
    ArtifactVerificationError,
    DeterministicLocalFfmpegAdapter,
    InMemoryMediaJobAdapter,
    MediaAdapterResult,
    MediaAdapterUnavailableError,
    MediaJobCoordinator,
    MediaJobError,
    MediaJobStateError,
    SqliteMediaJobAdapter,
    probe_media,
    verify_media_against_request,
)
from .comfyui import (
    COMFYUI_ADAPTER_ID,
    COMFYUI_CAPABILITY,
    COMFYUI_RUNTIME_ATTESTATION_SCHEMA,
    ComfyUIConfigurationError,
    ComfyUIProviderExecutionError,
    ComfyUIProviderResponseError,
    ComfyUIProviderTimeoutError,
    ComfyUIProviderUnavailableError,
    ComfyUIWan22Config,
    ComfyUIWan22VideoAdapter,
    build_comfyui_runtime_attestation,
    create_comfyui_wan22_adapter_from_environment,
)
from .composition import CompositionExecutionError, V4CompositionExecutor

__all__ = [
    "DeepSeekTextProvider",
    "FakeTextProvider",
    "ProviderConfigurationError",
    "ProviderMalformedResponseError",
    "ProviderTimeoutError",
    "ProviderUnavailableError",
    "TextGenerationRequest",
    "TextMessage",
    "TextProvider",
    "TextProviderError",
    "create_text_provider_from_environment",
    "ArtifactVerificationError",
    "DeterministicLocalFfmpegAdapter",
    "InMemoryMediaJobAdapter",
    "MediaAdapterResult",
    "MediaAdapterUnavailableError",
    "MediaJobCoordinator",
    "MediaJobError",
    "MediaJobStateError",
    "SqliteMediaJobAdapter",
    "probe_media",
    "verify_media_against_request",
    "COMFYUI_ADAPTER_ID",
    "COMFYUI_CAPABILITY",
    "COMFYUI_RUNTIME_ATTESTATION_SCHEMA",
    "ComfyUIConfigurationError",
    "ComfyUIProviderExecutionError",
    "ComfyUIProviderResponseError",
    "ComfyUIProviderTimeoutError",
    "ComfyUIProviderUnavailableError",
    "ComfyUIWan22Config",
    "ComfyUIWan22VideoAdapter",
    "build_comfyui_runtime_attestation",
    "create_comfyui_wan22_adapter_from_environment",
    "CompositionExecutionError",
    "V4CompositionExecutor",
]
